version: 2

models:
  - name: dim_zones
    description: >
      List of unique zones idefied by locationid. 
      Includes the service zone they correspond to (Green or yellow).

  - name: dm_monthly_zone_revenue
    description: >
      Aggregated table of all taxi trips corresponding to both service zones (Green and yellow) per pickup zone, month and service.
      The table contains monthly sums of the fare elements used to calculate the monthly revenue. 
      The table contains also monthly indicators like number of trips, and average trip distance. 
    columns:
      - name: revenue_monthly_total_amount
        description: Monthly sum of the the total_amount of the fare charged for the trip per pickup zone, month and service.
        tests:
            - not_null:
                severity: error
      
  - name: fact_trips
    description: >
      Taxi trips corresponding to both service zones (Green and yellow).
      The table contains records where both pickup and dropoff locations are valid and known zones. 
      Each record corresponds to a trip uniquely identified by tripid. 
    columns:
      - name: tripid
        data_type: string
        description: Primary key for this table, generated with a concatenation of vendorid+pickup_datetime

      - name: vendorid
        data_type: int64
        description: > 
                A code indicating the TPEP provider that provided the record.
                1 = Creative Mobile Technologies, LLC; 
                2 = VeriFone Inc.

      - name: service_type
        data_type: string
        description: Indicates whether this is a yellow or green taxi

      - name: ratecodeid
        data_type: int64
        description: >
          The final rate code in effect at the end of the trip.
            1 = Standard rate
            2 = JFK
            3 = Newark
            4 = Nassau or Westchester
            5 = Negotiated fare
            6 = Group ride

      - name: pickup_locationid
        data_type: int64
        description: locationid where the meter was engaged.

      - name: pickup_borough
        data_type: string
        description: borough where the meter was engaged.

      - name: pickup_zone
        data_type: string
        description: zone where the meter was engaged.

      - name: dropoff_locationid
        data_type: int64
        description: locationid where the meter was disengaged.

      - name: dropoff_borough
        data_type: string
        description: borough where the meter was disengaged.

      - name: dropoff_zone
        data_type: string
        description: zone where the meter was disengaged.

      - name: pickup_datetime
        data_type: timestamp
        description: The date and time when the meter was engaged.

      - name: dropoff_datetime
        data_type: timestamp
        description: The date and time when the meter was disengaged.

      - name: store_and_fwd_flag
        data_type: string
        description: > 
          This flag indicates whether the trip record was held in vehicle
          memory before sending to the vendor, aka “store and forward,”
          because the vehicle did not have a connection to the server.
            Y = store and forward trip
            N = not a store and forward trip

      - name: passenger_count
        data_type: int64
        description: The number of passengers in the vehicle. This is a driver-entered value.

      - name: trip_distance
        data_type: numeric
        description: The elapsed trip distance in miles reported by the taximeter.

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: > 
          The time-and-distance fare calculated by the meter.

      - name: extra
        data_type: numeric
        description: >
          Extra Miscellaneous extras and surcharges. Currently, this only includes
          the $0.50 and $1 rush hour and overnight charges.

      - name: mta_tax
        data_type: numeric
        description: >
          MTA_tax $0.50 MTA tax that is automatically triggered based on the metered
          rate in use.

      - name: tip_amount
        data_type: numeric
        description: > 
          Tip amount. This field is automatically populated for credit card
          tips. Cash tips are not included.

      - name: tolls_amount
        data_type: numeric
        description: Total amount of all tolls paid in trip.

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description:  > 
          $0.30 improvement surcharge assessed trips at the flag drop. The
          improvement surcharge began being levied in 2015.

      - name: total_amount
        data_type: numeric
        description: The total amount charged to passengers. Does not include cash tips.

      - name: payment_type
        data_type: int64
        description: A numeric code signifying how the passenger paid for the trip.

      - name: payment_type_description
        data_type: string
        description: How the passenger paid for the trip.