version: 2

models:
  - name: dm_monthly_zone_revenue
    description: >
      Aggregated table of all taxi trips corresponding to both service zones (Green and yellow) per pickup zone, month and service.
      The table contains monthly sums of the fare elements used to calculate the monthly revenue. 
      The table contains also monthly indicators like number of trips, and average trip distance. 
    columns:
      - name: revenue_monthly_total_amount
        description: Monthly sum of the the total_amount of the fare charged for the trip per pickup zone, month and service.
        tests:
            - not_null:
                severity: error

  - name: dm_taxi_trips_quarterly_revenue
    columns:
      - name: service_type
        data_type: string
        description: Indicates whether this is a yellow or green taxi.
        tests:
            - not_null:
                severity: error

      - name: year
        data_type: INT64
        description: The calendar year for this revenue calculation.
        tests:
            - not_null:
                severity: error
      
      - name: quarter
        data_type: INT64
        description: The calendar quarter for this revenue calculation (from 1 to 4).
        tests:
            - not_null:
                severity: error
      
      - name: quarterly_total_amount
        data_type: numeric
        description: The total revenue in the specified quarter of the specified year.
        tests:
            - not_null:
                severity: error

      - name: yoy_growth
        data_type: numeric
        description: The percentage year-on-year growth for the quarter (e.g. 2019/Q1 to 2020/Q1)

  - name: dm_taxi_monthly_fare_p95
    columns:
      - name: service_type
        data_type: string
        description: Indicates whether this is a yellow or green taxi.
        tests:
            - not_null:
                severity: error

      - name: year
        data_type: INT64
        description: The calendar year for this revenue calculation.
        tests:
            - not_null:
                severity: error
      
      - name: month
        data_type: INT64
        description: The calendar month for this revenue calculation.
        tests:
            - not_null:
                severity: error
      
      - name: fare_amount_p97
        data_type: numeric
        description: The (continuous) 97th percentile of the fare amount for the given year and month.
        tests:
            - not_null:
                severity: error

      - name: fare_amount_p95
        data_type: numeric
        description: The (continuous) 95th percentile of the fare amount for the given year and month.
        tests:
            - not_null:
                severity: error
      
      - name: fare_amount_p90
        data_type: numeric
        description: The (continuous) 90th percentile of the fare amount for the given year and month.
        tests:
            - not_null:
                severity: error

  - name: dm_fhv_monthly_zone_traveltime_p90
    description: >
      90th percentile of trip duration for each zone for each month (by pickup month).
    tests:
      - dbt_utils.unique_combination_of_columns:
            combination_of_columns:
                - year
                - month
                - pickup_locationid
                - dropoff_locationid
            severity: error
    columns:
      - name: year
        description: The calendar year for this aggregation
      
      - name: month
        description: The month of the calendar year for this aggregation

      - name: pickup_locationid
        description: locationid where the trips began.

      - name: pickup_borough
        data_type: string
        description: borough where the trips began.

      - name: pickup_zone
        data_type: string
        description: zone where the trips began.

      - name: dropoff_locationid 
        description: locationid where the trips ended.

      - name: dropoff_borough
        data_type: string
        description: borough where the trips ended.

      - name: dropoff_zone
        data_type: string
        description: zone where the trips ended.
      
      - name: trip_duration_p90
        data_type: numeric
        description: 90th percentile trip duration for the given zone pair and month.
        tests:
            - not_null:
                severity: error
          

      